test:
  data2: 421

server:
  address: 127.0.0.1
  port: '8000'

spring:
  config:
    import: "configserver:http://localhost:8888"
  application:
    name: "customer"
  profiles:
    active: "default"
  cloud:
    vault:
      host: localhost
      port: 8200
      uri: http://localhost:8200
      scheme: http
      authentication: TOKEN
      token: myroot
    config:
      enabled: true
      profile: "default"
      uri: "localhost:8888"
      import: "configserver:http://localhost:8888"
