test:
  data2: 421

#-----------------------------------------------#
server:
  port: 8000

#-----------------------------------------------#
swarmhost: 192.168.1.107

#-----------------------------------------------#
spring:
  config:
    import: configserver:http://${swarmhost}:8888/
  application:
    name: customer-service
  profiles:
    active:
      "default"
  cloud:
#    vault:
#      fail-fast: true
#      host: localhost
#      port: 8200
#      uri: http://localhost:8200
#      scheme: http
#      authentication: TOKEN
#      token: myroot
#      database:
#        enabled: true
#        role: my-role
#        backend: hotelapp
#        username-property: spring.datasource.username
#        password-property: spring.datasource.password
    config:
      fail-fast: true
      profile: default
      enabled: true
      uri: http://${swarmhost}:8888
      import: configserver:http://${swarmhost}:8888
#-----------------------------------------------#

eureka:
  client:
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${swarmhost}:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 120
    lease-expiration-duration-in-seconds: 240
#-----------------------------------------------#

#keycloak:
#  enabled: true
#  auth-server-url: http://${swarmhost}:8080/auth
#  realm: master
#  resource: hotelapp
#  public-client: true
#  ssl-required: external
#  use-resource-role-mappings: true
#  bearer-only: false

#keycloak.security-constraints[0].authRoles[0]: user
#keycloak.security-constraints[0].securityCollections[0].patterns[0]: /customers/*
#keycloak.principal-attribute: preferred_username
clientSecret: zjpSKq1HEj2RRqiIpb
#--------------------------#
management:
  endpoints:
  restart:
    enabled: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
endpoints:
  restart:
    enabled: true
