swarmhost: 192.168.1.107
spring:
  config:
    import: configserver:http://${swarmhost}:8888/
  application:
    name: gateway
  cloud:
    config:
      uri: http://${swarmhost}:8888
      #uri: http://${swarmhost}:8071
#-----------------------------------------------#
logging:
  level:
    io.hotely: DEBUG
    io.netflix: WARN
    org.springframework.web: WARN
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
