version: '3.9'

networks:
  perunanetti:
    driver: overlay
    driver_opts:
      encrypted: 'true'
    attachable: true
    external: true

# NOTE: Make sure you have defined the SWARMHOST environment variable to main host ip.
services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0 
    networks:
      - perunanetti
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
      KC_HOSTNAME: "${SWARMHOST}:8080"
      KC_HTTP_PORT: 8080
      KC_HTTP_ENABLED: 'true'
    command: start-dev
    healthcheck:
      test: curl http://127.0.0.1:8080/actuator/health || exit 1
      interval: 15s
      timeout: 10s
      retries: 10
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname == tau
      restart_policy:
        condition: on-failure
        max_attempts: 3
      update_config:
        order: 'stop-first'
      rollback_config:
        order: 'stop-first'
