server:
  port: 8888

logging.level.org.hibernate: ERROR
logging.level.root: warn
logging.level.: DEBUG

#--
#encrypt:
#  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo 
#--

spring:
  config:
    import:
      file:token.yml
  devtools:
    add-properties: true
    livereload.enabled: false
    restart.exclude: "public/**, static/**, templates/**" 
  profiles:
    active: native, vault
  application:
    name: "config"
  cloud:
#    vault:
#      kv:
#        enabled: true
#        backend: secret
#        profile-separator: '/'
#        default-context: application
#        profiles: local, cloud
#      authentication: TOKEN,
#      token: "s.mupS46becKPO6w35yXtID6pa"
#      scheme: "http"
#      kv.enabled: true
    config:
      server:
        native:
          searchLocations: [classpath:/config, classpath:/]
        vault:
          authentication: TOKEN
          token: "myroot"
          host: 127.0.0.1
          port: 8200
          scheme: http
          backend: secret
          defaultKey: application
          kvVersion: 2
          order: 1

#--

# Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
