test:
  test: 100
#--------------------------#
server:
  address: 127.0.0.1
  port: 8001
#--------------------------#
swarmhost: 192.168.1.107
#--------------------------#
spring:
  config:
    import: configserver:http://${swarmhost}:8888/
  application:
    name: "hotel"
  profiles:
    active: "default"
# TEMPORARY FOR TESTING
#  data:
#    cassandra:
#      local-datacenter: "datacenter1"
#      port: 9042
#     contact-points: 192.168.1.105:9042
#      contact-points: ${swarmhost}:9042
#      schema-action: "CREATE_IF_NOT_EXISTS"
#      username: "cassandra"
#      password: "cassandra"
#      keyspace-name: "hotelapp"
#      request:
#        timeout: 10s
#      connection:
#        connect-timeout: 10s
#        init-query-timeout: 10s
#--------------------------#
#  config:
#    import: "configserver:http://localhost:8888"
  cloud:
    config:
      enabled: true
      profile: "default"
      uri: ${swarmhost}:8888
      import: configserver:http://${swarmhost}:8888
#--------------------------#
eureka:
  client:
    serviceUrl:
      defaultZone: http://${swarmhost}:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
#--------------------------#
endpoints:
  restart:
    enabled: true
