test:
  test: 100
#--------------------------#
server:
  port: 8001

#--------------------------#
# Defines the master node ip
swarmhost: 192.168.1.107

#--------------------------#
spring:
  config:
    import: configserver:http://${swarmhost}:8888/
  application:
    name: hotel-service
  profiles:
    active: "default"
#--------------------------#
#  config:
#    import: "configserver:http://localhost:8888"
  cloud:
    config:
      enabled: true
      profile: "default"
      uri: http://${swarmhost}:8888
      import: configserver:http://${swarmhost}:8888

#--------------------------#

eureka:
  client:
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${swarmhost}:8761/eureka/
  instance:
    hostname: ${swarmhost}
    #preferIpAddress: true
    lease-renewal-interval-in-seconds: 120
    lease-expiration-duration-in-seconds: 240
#--------------------------#
management:
  endpoints:
  restart:
    enabled: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
endpoints:
  restart:
    enabled: true
