server:
  port: 8888
#
swarmhost: ${SWARMHOST}
#--
test:
  meme: 420
spring:
  application:
    name: config-server
  profiles:
    active: native, vault
  cloud:
    config:
      server:
        native:
          searchLocations: ['classpath:/config']
        vault:
          authentication: TOKEN
          token: "s.6cJrk6VbDvHzdpgflQAQgvdi"
          host: ${swarmhost}
          port: 8200
          scheme: http
          backend: secret
          defaultKey: application
          kvVersion: 2
          order: 1
#--

# Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
  restart:
    enabled: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
#--
logging.level.root: INFO
