server:
  port: 8888
#-- encrypt:
#  key: fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo 
#--
test:
  meme: 420
spring:
  application:
    name: config-server
  profiles:
    active: native, vault
  cloud:
    config:
      server:
        native:
          searchLocations: ['classpath:/config']
        vault:
          authentication: TOKEN
          token: "s.5ymlZAjKYIblv7YCLygCqVC3"
          host: 192.168.1.107
          port: 8200
          scheme: http
          backend: secret
          defaultKey: application
          kvVersion: 2
          order: 1
#--

# Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
  restart:
    enabled: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
#--
logging.level.root: INFO
