test:
  data: 222
  data2: 987
#------#

server:
  port: 8761
#------#
# Defines the master node ip
swarmhost: ${SWARMHOST}
#------#
spring:
  application:
    name: service-discovery
  profiles:
    active: "default"
  cloud:
    config:
      enabled: false
#------#
eureka:
  datacenter: hotely
  environment: production
  instance:
    preferIpAddress: true
    hostname: ${swarmhost} # Sets the Eureka instance hostname for the Eureka service.
  client:
    preferIpAddress: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${swarmhost}:${server.port}/eureka/
#------#
logging.level.com.netflix.eureka: OFF
logging.level.com.netflix.discovery: OFF
#------#
management:
  endpoints:
  restart:
    enabled: true
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
