test:
  data: '[{ "name": "John", "age": 30, "car": null }]'
  data2: 420
#--------------------------------------#

spring:
  profiles:
    active: native, vault
  cloud:
    vault:
      host: localhost
      port: 8200
      uri: http://localhost:8200
      scheme: http
      authentication: TOKEN
      token: "s.6cJrk6VbDvHzdpgflQAQgvdi"
  # DB setup
  data:
    cassandra:
      local-datacenter: "datacenter1"
      port: 9043
      contact-points: ${swarmhost}:9043
      schema-action: "CREATE_IF_NOT_EXISTS"
      username: ${dbuser}
      password: ${dbpass}
      keyspace-name: "hotelapp2"
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s
#--------------------------------------#
logging.level.root: "warn"
logging.level.org.springframework.web: "DEBUG"
logging.level.org.hibernate: "ERROR"
