server:
  port: 8072
#-----------------------------------------------#
eureka:
  instance:
    preferIpAddress: true
  client:
    preferIpAddress: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: ${EUREKA_URI:http://${swarmhost}:8761/eureka}
#-----------------------------------------------#
spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
    vault:
      token: s.YYNCvN6yyWQiVK76xdk8wC5d
#      routes:
#        - id: customer
#          uri: lb://customer
#          predicates:
#            - Path=/customer/**
#          filters:
#            - RewritePath=/customer/(?<path>.*), /$\{path}
#-----------------------------------------------#
management:
  endpoints:
    web:
      exposure:
        include: "*"
